// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Smart_Saver_API.Data;

namespace Smart_Saver_API.Migrations
{
    [DbContext(typeof(Smart_Saver_APIContext))]
    [Migration("20201217121212_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Smart_Saver_API.Models.CategoriesDB", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("categoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("categoryId");

                    b.ToTable("CategoriesDB");
                });

            modelBuilder.Entity("Smart_Saver_API.Models.ExpenseDB", b =>
                {
                    b.Property<int>("expenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("expenseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("expenseCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("expenseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("expenseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("expenseId");

                    b.ToTable("ExpenseDB");
                });

            modelBuilder.Entity("Smart_Saver_API.Models.GoalDB", b =>
                {
                    b.Property<int>("goalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("goalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("goalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("goalName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("goalId");

                    b.ToTable("GoalDB");
                });

            modelBuilder.Entity("Smart_Saver_API.Models.IncomeDB", b =>
                {
                    b.Property<int>("incomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("incomeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("incomeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("incomeId");

                    b.ToTable("IncomeDB");
                });

            modelBuilder.Entity("Smart_Saver_API.Models.ReccuringIncomeDB", b =>
                {
                    b.Property<int>("reccuringincomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("reccuringincomeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("reccuringincomeDateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("reccuringincomeDateUntil")
                        .HasColumnType("datetime2");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("reccuringincomeId");

                    b.ToTable("ReccuringIncomeDB");
                });

            modelBuilder.Entity("Smart_Saver_API.Models.UserDB", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("userAge")
                        .HasColumnType("int");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("userSurname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("userId");

                    b.ToTable("UserDB");
                });
#pragma warning restore 612, 618
        }
    }
}
